import turtle

turtle.Screen().bgcolor("black")
t = turtle.Turtle()
t.goto(0, 0)
t.width(5)
t.color("white")

# 500, 600, 700
t.penup()
t.goto(-250, 50)
t.pendown()
t.forward(200)
t.penup()
t.forward(100)
t.pendown()
t.forward(200)
t.right(90)
t.forward(100)
t.right(90)
t.forward(50)
t.penup()
t.forward(80)
t.pendown()
t.forward(240)
t.penup()
t.forward(80)
t.pendown()
t.forward(50)
t.right(90)
t.forward(100)
t.penup()

t.goto(-300, 80)
t.right(90)
t.pendown()
t.forward(600)
t.right(90)
t.forward(160)
t.right(90)
t.forward(600)
t.right(90)
t.forward(160)
t.penup()

t.goto(-350, 110)
t.right(90)
t.forward(50)
t.pendown()
t.forward(100)
t.penup()
t.forward(100)
t.pendown()
t.forward(100)
t.penup()
t.forward(100)
t.pendown()
t.forward(100)
t.penup()
t.forward(100)
t.pendown()
t.forward(50)
t.right(90)
t.forward(150)
t.penup()
t.forward(70)
t.pendown()
t.right(90)

# t.forward(700)
t.forward(200)
t.penup()
t.forward(120)
t.pendown()
t.forward(350)
t.penup()
t.forward(30)
t.pendown()
t.right(90)
t.forward(220)
t.penup()
t.goto(-200,-45)

t.color("Cyan")
t.write("I", font=("Consolas", 60, "bold"))
t.penup()
t.right(90)
t.forward(60)
t.pendown()
t.write("N", font=("Consolas", 60, "bold"))
t.penup()
t.forward(60)
t.pendown()
t.write("F", font=("Consolas", 60, "bold"))
t.penup()
t.forward(60)
t.pendown()
t.write("O", font=("Consolas", 60, "bold"))
t.penup()
t.forward(60)
t.pendown()
t.write("S", font=("Consolas", 60, "bold"))
t.penup()
t.forward(60)
t.pendown()
t.write("Y", font=("Consolas", 60, "bold"))
t.penup()
t.forward(60)
t.pendown()
t.write("S", font=("Consolas", 60, "bold"))

t.hideturtle()
turtle.done()